def display_ticket(ticket):
    print("========== HelpDesk Ticket ==========")
    print(f"Student Name: {ticket["name"]}")
    print(f"Student ID: {ticket["id"]}")
    print(f"Issue: {ticket["issue"]}")
    print(f"Location: {ticket["location"]}")
    print(f"Priority: {ticket["priority"]}")
    print(f"Technician: {ticket["technician"]}")
    print(f"Status: {ticket["status"]}")
    print("======================================")